spring.application.name=project_gr1

# Database - PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/hsf_prj
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Static Resources
spring.web.resources.static-locations=classpath:/static/
spring.web.resources.add-mappings=true

# PayOS Configuration
payos.client-id=1768729c-6c57-4b58-932a-b13ab4c3d3a8
payos.api-key=102633ce-f37e-4096-8e84-e4f97c942ed3
payos.checksum-key=1c91f2e018483d863f86b703797cb0ce4a1ae7afddf460f0daac4db72c2ea469
payos.return-url=http://localhost:8080/wallet?payos=success
payos.cancel-url=http://localhost:8080/wallet?payos=cancel
